version: '3.7'

services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - '${REDIS_PORT:-6379}:6379'

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - '${DB_PORT:-5432}:5432'

volumes:
  redis:
  postgres:
